config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, path: 'admins', controllers: { sessions: "admins/sessions", registrations: "admins/registrations" }
  devise_for :users, path: 'users', controllers: { sessions: "users/sessions" }
  get 'home/index'
  get 'home/filter_search', to: 'home#filter_search'
  get 'home/places', to: 'home#places'
  root to: 'home#index'
  get 'admins/index', to: 'admins#index' 
  resources :car_brands do
    resources :car_models
  end
  resources :car_cities
  resources :car_registration_states
  resources :car_variants
  resources :car_kilometer_drivens
  resources :car_registration_years
  resources :car_costs

  get 'users/index', to: 'users#index'
  
  resources :cars do 
    member do 
      get 'quotation'
      get 'appointment'
    end 
  end 
  resources :appointments do 
    member do 
      get 'details'
      get 'approve'
      get 'schedule'
      patch 'save_schedule'
      get 'verify'
      get 'soldout'

    end
    collection do
      get 'my_appointments'
      get 'status'
    end
  end
  resources :notifications do
    collection do
      post 'mark_as_read'
    end
  end
  #get 'cars/quotation', to: 'cars#quotation'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/car_variant.rb
class CarVariant < ApplicationRecord
end

app/controllers/car_variants_controller.rb
class CarVariantsController < ApplicationController
  before_action :get_car_variant, except: [:index, :new, :create]

  def index
    @car_variants = CarVariant.all
  end

  def show
  end

  def new
    @car_variant = CarVariant.new
  end

  def edit 
  end

  def create
    @car_variant = CarVariant.new(car_variant_params)
    if @car_variant.save
      generate_flash "Car variant has been succesfully created"
      redirect_to @car_variant
    else
      generate_flash "Failed to create Car variant"
      render "new"
    end
  end

  def update 
    if @car_variant.update(car_variant_params)
      generate_flash "Car variant has been succesfully Updated"
      redirect_to car_variants_path
    else
      generate_flash "Failed to update Car variant"
      render "edit"
    end
  end

  def destroy
    @car_variant.destroy
    generate_flash "Car variant has been succesfully destroyed"
    redirect_to car_variants_path
  end

  def generate_flash(msg)
    flash[:notice] = msg
  end

  def get_car_variant
    @car_variant = CarVariant.find(params[:id])
  end

  private
    def car_variant_params
      params.require(:car_variant).permit(:name)     
    end
end

app/helpers/car_variants_helper.rb
module CarVariantsHelper
end

app/views/car_variants/_form.html.erb
<%= render partial: "shared/form", locals: {var_1: @car_variant} %>

app/views/car_variants/edit.html.erb
<h1> Edit Car Variant Detail </h1>

<%= render  "form" %>
 
<%= link_to "Back", car_variants_path %>

app/views/car_variants/index.html.erb
<h1>CRUD operations for Car variants</h1>
<%= link_to "Add New variant", new_car_variant_path %> |
<%= link_to "Go to Admin Dashboard", admins_index_path %>


<% if @car_variants != [] %>

<h3>Listing of Car variants</h3>
<table>
  <tr>
    <th>Name</th>
    <th colspan="3"></th>
  </tr>
 
  <% @car_variants.each do |c| %>
    <tr>
      <td><%= c.name %></td>
      <td><%= link_to "Show", car_variant_path(c) %></td>
      <td><%= link_to "Edit", edit_car_variant_path(c) %></td>
      <td><%= link_to "Destroy", car_variant_path(c),
              method: :delete,
              data: { confirm: "Are you sure?" } %></td>
    </tr>
  <% end %>
</table>
<% end %>

app/views/car_variants/new.html.erb
<h1>New Car Variant</h1>
 
<%= render "form" %>

<%= link_to "Back", car_variants_path %>

app/views/car_variants/show.html.erb
<p>
  <strong>Car Variant:</strong>
  <%= @car_variant.name %>
</p>

<%= link_to "Edit", edit_car_variant_path(@car_variant) %> |
<%= link_to "Back", car_variants_path %>