config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, path: 'admins', controllers: { sessions: "admins/sessions", registrations: "admins/registrations" }
  devise_for :users, path: 'users', controllers: { sessions: "users/sessions" }
  get 'home/index'
  get 'home/filter_search', to: 'home#filter_search'
  get 'home/places', to: 'home#places'
  root to: 'home#index'
  get 'admins/index', to: 'admins#index' 
  resources :car_brands do
    resources :car_models
  end
  resources :car_cities
  resources :car_registration_states
  resources :car_variants
  resources :car_kilometer_drivens
  resources :car_registration_years
  resources :car_costs

  get 'users/index', to: 'users#index'
  
  resources :cars do 
    member do 
      get 'quotation'
      get 'appointment'
    end 
  end 
  resources :appointments do 
    member do 
      get 'details'
      get 'approve'
      get 'schedule'
      patch 'save_schedule'
      get 'verify'
      get 'soldout'

    end
    collection do
      get 'my_appointments'
      get 'status'
    end
  end
  resources :notifications do
    collection do
      post 'mark_as_read'
    end
  end
  #get 'cars/quotation', to: 'cars#quotation'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
end

app/models/car.rb
require 'elasticsearch/model'

class Car < ApplicationRecord
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  def as_indexed_json(options = {})
    self.as_json(
      only: [:city, :brand, :model, :registration_year, :variant, :registration_state, :kilometer_driven, :condition]
      
    )
  end

  def self.filtered_search(search, city, brand, model, registration_year, variant, registration_state, kilometer_driven)
	
	search_query =
		{
		query: {
		        bool: {
		            # must: {
		            #    multi_match: {
		            #         query: search,
		            #         fields: [:city, :brand, :model, :registration_year, :variant, :registration_state, :kilometer_driven]
		            #     	}
		            # 	}
		            # filter: {
		            # 	bool: {
		            #         must: {
		            #             match: { :city => city }
		            #         	}
		            #     	}
		            # }
		        	}
				}
			}
		

		filter_query = {		
		                bool: {
		                    should: [{
		                        # match: { :city => city }
		                    	}]

		                	}		            	
		            }

		#only search
		text_query= {
			multi_match: {
		                    query: search,
		                    fields: [:city, :brand, :model, :registration_year, :variant, :registration_state, :kilometer_driven]
		                	}
		}
		search_query[:query][:bool].store(:must, text_query) unless search.blank?

		#search and filter
		
		#print "city array ",cities
		unless registration_state.blank?
			registration_state.each do |r_s|
				registration_state_filter = { match:{ registration_state: r_s }}
				filter_query[:bool][:should] << registration_state_filter
			end
		end
		unless city.blank?
			city.each do |c|
				city_filter = { match:{ city: c}}
				filter_query[:bool][:should] << city_filter
			end
			end
		unless brand.blank?
			brand.each do |b|
				brand_filter = { match:{ brand: b }}
				filter_query[:bool][:should] << brand_filter
			end
			end
		unless model.blank?	
			model.each do |m|
				model_filter = { match:{ model: m }}
				filter_query[:bool][:should] << model_filter
			end
			end
		unless variant.blank?
			variant.each do |v|
				variant_filter = { match:{ variant: v }}
				filter_query[:bool][:should] << variant_filter 
			end
			end
		unless registration_year.blank?
			registration_year.each do |r_y|
				registration_year_filter = { match:{ registration_year: r_y }}
				filter_query[:bool][:should] << registration_year_filter
			end
			end
		unless kilometer_driven.blank?
			kilometer_driven.each do |k_d|
				kilometer_driven_filter = { match:{ kilometer_driven: k_d }}
				filter_query[:bool][:should] << kilometer_driven_filter
			end
			end


		#print "filter query ", filter_query

		# city_filter = { match:{ city: city}}
		# filter_query[:bool][:must] << city_filter unless city.blank?

		# brand_filter = { match:{ brand: brand }}
		# filter_query[:bool][:must] << brand_filter unless brand.blank?

		# model_filter = { match:{ model: model }}
		# filter_query[:bool][:must] << model_filter unless model.blank?

		# registration_year_filter = { match:{ registration_year: registration_year }}
		# filter_query[:bool][:must] << registration_year_filter unless registration_year.blank?

		# variant_filter = { match:{ variant: variant }}
		# filter_query[:bool][:must] << variant_filter unless variant.blank?

		# registration_state_filter = { match:{ registration_state: registration_state }}
		# filter_query[:bool][:must] << registration_state_filter unless registration_state.blank?

		# kilometer_driven_filter = { match:{ kilometer_driven: kilometer_driven }}
		# filter_query[:bool][:must] << kilometer_driven_filter unless kilometer_driven.blank?

		filter_query[:bool][:should].shift

		search_query[:query][:bool].store(:filter, filter_query)
		# unless ( city.blank? or brand.blank? or model.blank? or registration_year.blank? or variant.blank? or registration_state.blank? or kilometer_driven.blank? )

		#only filter

		#search_query[:query][:bool].store(:filter, filter_query) unless city.p?
		
		self.search(
			search_query
		)
		
		#  	self.search({
		#       "query": {
		#         "bool": {
		#             "must": {
		#                "multi_match": {
		#                     "query": search,
		#                     "fields": [:city, :brand, :model, :registration_year, :variant, :registration_state, :kilometer_driven]
		#                 	}
		#             	},
		#             "filter": {
		#                 "bool": {
		#                     "must": {
		#                         "match": { :city => city }
		#                     	}
		#                 	}
		#             	}
		#         	}
		# 		}
		
		# })
		

	end

  # settings do
  #   mappings dynamic: false do
  #     indexes :city, type: :text
  #     indexes :brand, type: :text, analyzer: :english
  #     indexes :model, type: :text, analyzer: :english
  #     indexes :registration_year, type: :text, analyzer: :english
  #     indexes :variant, type: :text, analyzer: :english
  #     indexes :registration_state, type: :text, analyzer: :english
  #     indexes :kilometer_driven, type: :text, analyzer: :english
  #     indexes :condition, type: :text, analyzer: :english
  #   end
  # end

  
end

#Car.import

app/models/car_brand.rb
class CarBrand < ApplicationRecord
  has_many :car_models, dependent: :destroy
end

app/models/car_city.rb
class CarCity < ApplicationRecord
end

app/models/car_cost.rb
class CarCost < ApplicationRecord
end

app/models/car_model.rb
class CarModel < ApplicationRecord
  belongs_to :car_brand
end

app/models/car_variant.rb
class CarVariant < ApplicationRecord
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :recipient, class_name: "User"
  belongs_to :notifiable, polymorphic: true

	scope :unread, ->{ where(read_at: nil) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, 
         :confirmable, :lockable

  has_many :notifications, foreign_key: :recipient_id
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/car_brands_helper.rb
module CarBrandsHelper
end

app/helpers/car_cities_helper.rb
module CarCitiesHelper
end

app/helpers/car_costs_helper.rb
module CarCostsHelper
end

app/helpers/car_models_helper.rb
module CarModelsHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/index.html.erb
<div class="jumbotron">
  <div class="container">
    <h1 class="display-3 text-center ">Admin Dashboard</h1>
  </div>
</div>
<div class="card-group text-center">
  <div class="card">
    <div class="card-header">Car Brands and Models</div>
    <div class="card-body">
      <%= link_to 'Add new', car_brands_path, class: "btn btn-dark " %>
    </div>
  </div>
  <div class="card">
    <div class="card-header">Car Registration City</div>
    <div class="card-body">
      <%= link_to 'Add new', car_cities_path, class: "btn btn-dark"  %>
    </div>
  </div>
</div>
  <div class="card-group text-center">
  <div class="card">
    <div class="card-header">Car Registration State</div>
    <div class="card-body">
      <%= link_to 'Add new', car_registration_states_path, class: "btn btn-dark"  %>
    </div>
  </div>
  <div class="card">
    <div class="card-header">Car Variants</div>
    <div class="card-body">
      <%= link_to 'Add new', car_variants_path, class: "btn btn-dark"  %>
    </div>
  </div>
</div>
  <div class="card-group text-center">
  <div class="card">
    <div class="card-header">Ranges of the kilometer driven by a car</div>
    <div class="card-body">
      <%= link_to 'Add new', car_kilometer_drivens_path, class: "btn btn-dark"  %>
    </div>
  </div>
  <div class="card">
    <div class="card-header">Car Registration year</div>
    <div class="card-body">
      <%= link_to 'Add new', car_registration_years_path, class: "btn btn-dark"  %>
    </div>
  </div>
</div>
  <div class="card-group text-center">
  <div class="card">
    <div class="card-header">Car Costs and Conditions</div>
    <div class="card-body">
      <%= link_to 'Add new', car_costs_path, class: "btn btn-dark"  %></p>
    </div>
  </div>
  <div class="card">
    <div class="card-header">Manage Appointments</div>
    <div class="card-body">
      <%= link_to 'details', appointments_path, class: "btn btn-dark"  %>
    </div>
  </div>
</div>

app/views/shared/_error.html.erb
<% if var.errors.any? %>
    <div>
      <h2>
        <%= pluralize(var.errors.count, "error") %> 
        prohibited this Client details from being saved:
      </h2>
      <ul>
        <% var.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  

app/views/shared/_form.html.erb
<%= form_for var_1 do |form| %>
  <%= render :partial => "shared/error", locals: {var: var_1} %>
  <p>
    <%= form.label :name %>
    <br>
    <%= form.text_field :name , required: true %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>