config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, path: 'admins', controllers: { sessions: "admins/sessions", registrations: "admins/registrations" }
  devise_for :users, path: 'users', controllers: { sessions: "users/sessions" }
  get 'home/index'
  get 'home/filter_search', to: 'home#filter_search'
  get 'home/places', to: 'home#places'
  root to: 'home#index'
  get 'admins/index', to: 'admins#index' 
  resources :car_brands do
    resources :car_models
  end
  resources :car_cities
  resources :car_registration_states
  resources :car_variants
  resources :car_kilometer_drivens
  resources :car_registration_years
  resources :car_costs

  get 'users/index', to: 'users#index'
  
  resources :cars do 
    member do 
      get 'quotation'
      get 'appointment'
    end 
  end 
  resources :appointments do 
    member do 
      get 'details'
      get 'approve'
      get 'schedule'
      patch 'save_schedule'
      get 'verify'
      get 'soldout'

    end
    collection do
      get 'my_appointments'
      get 'status'
    end
  end
  resources :notifications do
    collection do
      post 'mark_as_read'
    end
  end
  #get 'cars/quotation', to: 'cars#quotation'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/car_cost.rb
class CarCost < ApplicationRecord
end

app/controllers/car_costs_controller.rb
class CarCostsController < ApplicationController
  before_action :get_car_cost, except: [:index, :new, :create]

  def index
    @car_costs = CarCost.all
  end

  def show
  end

  def new
    @car_cost = CarCost.new
  end

  def edit
  end

  def create
    @car_cost = CarCost.new(car_cost_params)
    if @car_cost.save
      generate_flash "Car Cost has been succesfully created"
      redirect_to @car_cost
    else
      generate_flash "Failed to create Car cost"
      render "new"
    end
  end

  def update 
    if @car_cost.update(car_cost_params)
      generate_flash "Car Cost has been succesfully Updated"
      redirect_to car_costs_path
    else
      generate_flash "Failed to update Car Cost"
      render "edit"
    end
  end

  def destroy
    @car_cost.destroy
    generate_flash "Car Cost has been succesfully destroyed"
    redirect_to car_costs_path
  end

  def generate_flash(msg)
    flash[:notice] = msg
  end

  def get_car_cost
    @car_cost = CarCost.find(params[:id])
  end

  private
    def car_cost_params
      params.require(:car_cost).permit(:condition, :cost)     
    end
end

app/helpers/car_costs_helper.rb
module CarCostsHelper
end

app/views/car_costs/_form.html.erb
<%= form_for @car_cost do |form| %>
  <%= render partial: "shared/error", locals: {var: @car_cost} %>
  <p>
    <%= form.label :condition %>
    <br>
    <%= form.text_field :condition , required: true %>
  </p>
  <p>
    <%= form.label :cost %>
    <br>
    <%= form.text_field :cost , required: true %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/car_costs/edit.html.erb
<h1> Edit Car Cost Detail </h1>

<%= render  "form" %>
 
<%= link_to "Back", car_costs_path %>

app/views/car_costs/index.html.erb
<h1>CRUD operations for Car Costs</h1>
<%= link_to "Add New ", new_car_cost_path %> |
<%= link_to "Go to Admin Dashboard", admins_index_path %>

<% if @car_costs != [] %>

<h3>Listing of Car Conditions and their respective Cost</h3>
<table>
  <tr>
    <th>Condition</th>
    <th>Cost</th>
    <th colspan="3"></th>
  </tr>
 
  <% @car_costs.each do |c| %>
    <tr>
      <td><%= c.condition %></td>
      <td><%= c.cost %></td>
      <td><%= link_to "Show", car_cost_path(c) %></td>
      <td><%= link_to "Edit", edit_car_cost_path(c) %></td>
      <td><%= link_to "Destroy", car_cost_path(c),
              method: :delete,
              data: { confirm: "Are you sure?" } %></td>
    </tr>
  <% end %>
</table>
<% end %>

app/views/car_costs/new.html.erb
<h1>New Car cost details</h1>
 
<%= render "form" %>

<%= link_to "Back", car_costs_path %>

app/views/car_costs/show.html.erb
<p>
  <strong>Car Condition:</strong>
  <%= @car_cost.condition %>
</p>
<p>
  <strong>Car Cost:</strong>
  <%= @car_cost.cost %>
</p>
<%= link_to "Edit", edit_car_cost_path(@car_cost) %> |
<%= link_to "Back", car_costs_path %>