config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, path: 'admins', controllers: { sessions: "admins/sessions", registrations: "admins/registrations" }
  devise_for :users, path: 'users', controllers: { sessions: "users/sessions" }
  get 'home/index'
  get 'home/filter_search', to: 'home#filter_search'
  get 'home/places', to: 'home#places'
  root to: 'home#index'
  get 'admins/index', to: 'admins#index' 
  resources :car_brands do
    resources :car_models
  end
  resources :car_cities
  resources :car_registration_states
  resources :car_variants
  resources :car_kilometer_drivens
  resources :car_registration_years
  resources :car_costs

  get 'users/index', to: 'users#index'
  
  resources :cars do 
    member do 
      get 'quotation'
      get 'appointment'
    end 
  end 
  resources :appointments do 
    member do 
      get 'details'
      get 'approve'
      get 'schedule'
      patch 'save_schedule'
      get 'verify'
      get 'soldout'

    end
    collection do
      get 'my_appointments'
      get 'status'
    end
  end
  resources :notifications do
    collection do
      post 'mark_as_read'
    end
  end
  #get 'cars/quotation', to: 'cars#quotation'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/car_brand.rb
class CarBrand < ApplicationRecord
  has_many :car_models, dependent: :destroy
end

app/controllers/car_brands_controller.rb
class CarBrandsController < ApplicationController
  before_action :get_car_brand, except: [:index, :new, :create]

  def index
    @car_brands = CarBrand.all
  end

  def show
    
  end

  def new
    @car_brand = CarBrand.new
  end

  def edit 
  end

  def create
    @car_brand = CarBrand.new(car_brand_params)
    if @car_brand.save
      generate_flash "Car Brand has been succesfully created"
      redirect_to @car_brand
    else
      generate_flash "Failed to create Car Brand"
      render "new"
    end
  end
  def update 
    if @car_brand.update(car_brand_params)
      generate_flash "Car Brand has been succesfully Updated"
      redirect_to car_brands_path
    else
      generate_flash "Failed to update Car Brand"
      render "edit"
    end
  end

  def destroy
    @car_brand.destroy
    generate_flash "Car Brand has been succesfully destroyed"
    redirect_to car_brands_path
  end

  def generate_flash(msg)
    flash[:notice] = msg
  end

  def get_car_brand
    @car_brand = CarBrand.find(params[:id])
  end

  private
    def car_brand_params
      params.require(:car_brand).permit(:name)     
    end
end

app/helpers/car_brands_helper.rb
module CarBrandsHelper
end

app/views/car_brands/_form.html.erb
<%= render partial: "shared/form", locals: {var_1: @car_brand} %>

app/views/car_brands/edit.html.erb
<h1> Edit Car Brand Detail </h1>

<%= render  "form" %>
 
<%= link_to "Back", car_brands_path %>

app/views/car_brands/index.html.erb
<h1>CRUD operations for Car Brands and models</h1>
<%= link_to "Add New Car Brand", new_car_brand_path %> |
<%= link_to "Go to Admin Dashboard", admins_index_path %>


<% if @car_brands != [] %>
<h3>Listing of Car Brands and their models inside it</h3>
<table>
  <tr>
    <th>Name</th>
    <th colspan="3"></th>
  </tr>
 
  <% @car_brands.each do |c| %>
    <tr>
      <td><%= c.name %></td>
      <td><%= link_to "Show", car_brand_path(c) %></td>
      <td><%= link_to "Edit", edit_car_brand_path(c) %></td>
      <td><%= link_to "Destroy", car_brand_path(c),
              method: :delete,
              data: { confirm: "Are you sure?" } %></td>
    </tr>
  <% end %>
</table>
<% end %>

app/views/car_brands/new.html.erb
<h1>New Car Brand</h1>
 
<%= render "form" %>

<%= link_to "Back", car_brands_path %>

app/views/car_brands/show.html.erb
<p>
  <strong>Car Brand Name:</strong>
  <%= @car_brand.name %>
</p>
<h2>Car Models</h2>
<%= render @car_brand.car_models %>


<h2>Add a Car Model:</h2>
<%= render 'car_models/form' %>

<%= link_to "Edit", edit_car_brand_path(@car_brand) %> |
<%= link_to "Back", car_brands_path %>